-- CreateEnum
CREATE TYPE "CuisineType" AS ENUM ('NORTH_INDIAN', 'SOUTH_INDIAN', 'CHINESE', 'ITALIAN', 'MEXICAN', 'CONTINENTAL', 'THAI', 'JAPANESE', 'MEDITERRANEAN', 'STREET_FOOD', 'LOCAL_DELICACY');

-- CreateEnum
CREATE TYPE "IndianState" AS ENUM ('ANDHRA_PRADESH', 'ARUNACHAL_PRADESH', 'ASSAM', 'BIHAR', 'CHHATTISGARH', 'GOA', 'GUJARAT', 'HARYANA', 'HIMACHAL_PRADESH', 'JHARKHAND', 'KARNATAKA', 'KERALA', 'MADHYA_PRADESH', 'MAHARASHTRA', 'MANIPUR', 'MEGHALAYA', 'MIZORAM', 'NAGALAND', 'ODISHA', 'PUNJAB', 'RAJASTHAN', 'SIKKIM', 'TAMIL_NADU', 'TELANGANA', 'TRIPURA', 'UTTAR_PRADESH', 'UTTARAKHAND', 'WEST_BENGAL', 'ANDAMAN_AND_NICOBAR_ISLANDS', 'CHANDIGARH', 'DADRA_AND_NAGAR_HAVELI_AND_DAMAN_AND_DIU', 'DELHI', 'JAMMU_AND_KASHMIR', 'LADAKH', 'LAKSHADWEEP', 'PUDUCHERRY');

-- CreateTable
CREATE TABLE "Eateries" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "cusineType" "CuisineType" NOT NULL DEFAULT 'LOCAL_DELICACY',
    "email" TEXT NOT NULL,
    "phone" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "addressLineOne" TEXT NOT NULL,
    "addressLineTwo" TEXT,
    "city" TEXT NOT NULL,
    "state" "IndianState" NOT NULL,
    "pincode" TEXT NOT NULL,
    "operatingHours" JSONB,
    "isOpen" BOOLEAN NOT NULL DEFAULT false,
    "images" TEXT[],

    CONSTRAINT "Eateries_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "Eateries" ADD CONSTRAINT "Eateries_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
